name: Build/Deploy MSVC Windows

on:
  push:
    branches: [ main, features/github-actions ]

jobs:
  # Constants to simplify things
  
  build:
    name: "Build"
    runs-on: windows-2019

    steps:
    
    ## Checkout Git repo
    - name: Checkout Git Repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    # Then install libarchive + libpng-apng for all targets.
    - name: Restore from cache and install vcpkg + libraries (libarchive, libpng-apng)
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgArguments: '@${{ env.VCPKGRESPONSEFILE }}'
        # libpng-apng portfile fixed (microsoft/vcpkg#13837) as of 2020.10.13
        # This commit ID dates 6/4/2021 (not tied to a tag)
        vcpkgGitCommitId: b2544fd780b2e9a05d903314cbbd37268ba43d81
        appendedCacheKey: 23445
        setupOnly: true

    - name: Patch vcpkg cmake files
      shell: cmd
      run: |
        echo Updating: vcpkg\scripts\cmake\vcpkg_execute_required_process.cmake
        copy /b /v /y .github\workflows\vcpkg-patches\vcpkg_execute_required_process.cmake vcpkg\scripts\cmake\vcpkg_execute_required_process.cmake
        ::echo Creating directory to prevent failure: vcpkg\downloads
        ::md vcpkg\downloads

    - name: Install packages
      shell: cmd
      run: |
        .\vcpkg\vcpkg install --debug bzip2 || echo FAILED
        echo Start Env Check
        echo == Print version
        "C:/Program Files/Git/bin/git.exe" --version || echo Git not found
        ::echo == Run tree
        ::tree D:/a/github-actions-test/github-actions-test/vcpkg/downloads || echo Tree failed
        ::echo == cd into dir
        ::cd D:/a/github-actions-test/github-actions-test/vcpkg/downloads || echo cd failed
        ::echo == Attempt to git init
        ::"C:/Program Files/Git/bin/git.exe" init git-tmp || echo Git init failed
        echo End GitHub Actions Environment Check
        ::"C:\Program Files\CMake\bin\cmake.exe" --debug-output --trace -Wdev --debug -DALL_FEATURES= -DCURRENT_PORT_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/ports/fdlibm -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=fdlibm -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=D:/a/github-actions-test/github-actions-test/vcpkg/downloads -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=D:\a\github-actions-test\github-actions-test\vcpkg\triplets\x86-windows.cmake" -DVCPKG_BASE_VERSION=2021-05-05 -DVCPKG_CONCURRENCY=3 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=C:/Program Files/Git/bin/git.exe" -DVCPKG_ROOT_DIR=D:/a/github-actions-test/github-actions-test/vcpkg -DPACKAGES_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/packages -DBUILDTREES_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/installed -DDOWNLOADS=D:/a/github-actions-test/github-actions-test/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\a\github-actions-test\github-actions-test\vcpkg\scripts\ports.cmake
